#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pro_Salles.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Salles_DB")]
	public partial class Pro_SallesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    partial void InsertUserSettingsProfileProperty(UserSettingsProfileProperty instance);
    partial void UpdateUserSettingsProfileProperty(UserSettingsProfileProperty instance);
    partial void DeleteUserSettingsProfileProperty(UserSettingsProfileProperty instance);
    partial void InsertCompany_Info(Company_Info instance);
    partial void UpdateCompany_Info(Company_Info instance);
    partial void DeleteCompany_Info(Company_Info instance);
    partial void InsertDrower(Drower instance);
    partial void UpdateDrower(Drower instance);
    partial void DeleteDrower(Drower instance);
    partial void InsertInvoice_Detail(Invoice_Detail instance);
    partial void UpdateInvoice_Detail(Invoice_Detail instance);
    partial void DeleteInvoice_Detail(Invoice_Detail instance);
    partial void InsertInvoice_Header(Invoice_Header instance);
    partial void UpdateInvoice_Header(Invoice_Header instance);
    partial void DeleteInvoice_Header(Invoice_Header instance);
    partial void InsertJournal(Journal instance);
    partial void UpdateJournal(Journal instance);
    partial void DeleteJournal(Journal instance);
    partial void InsertProduct_Category(Product_Category instance);
    partial void UpdateProduct_Category(Product_Category instance);
    partial void DeleteProduct_Category(Product_Category instance);
    partial void InsertProduct_Unit(Product_Unit instance);
    partial void UpdateProduct_Unit(Product_Unit instance);
    partial void DeleteProduct_Unit(Product_Unit instance);
    partial void InsertStore_Log(Store_Log instance);
    partial void UpdateStore_Log(Store_Log instance);
    partial void DeleteStore_Log(Store_Log instance);
    partial void InsertStore(Store instance);
    partial void UpdateStore(Store instance);
    partial void DeleteStore(Store instance);
    partial void InsertUnits_name(Units_name instance);
    partial void UpdateUnits_name(Units_name instance);
    partial void DeleteUnits_name(Units_name instance);
    partial void InsertUser_Access_Profile_Detail(User_Access_Profile_Detail instance);
    partial void UpdateUser_Access_Profile_Detail(User_Access_Profile_Detail instance);
    partial void DeleteUser_Access_Profile_Detail(User_Access_Profile_Detail instance);
    partial void InsertUser_Access_Profile_Name(User_Access_Profile_Name instance);
    partial void UpdateUser_Access_Profile_Name(User_Access_Profile_Name instance);
    partial void DeleteUser_Access_Profile_Name(User_Access_Profile_Name instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertUserSettingsProfile(UserSettingsProfile instance);
    partial void UpdateUserSettingsProfile(UserSettingsProfile instance);
    partial void DeleteUserSettingsProfile(UserSettingsProfile instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    partial void InsertCustomersAndVendor(CustomersAndVendor instance);
    partial void UpdateCustomersAndVendor(CustomersAndVendor instance);
    partial void DeleteCustomersAndVendor(CustomersAndVendor instance);
    #endregion
		
		public Pro_SallesDataContext() : 
				base(global::Pro_Salles.Properties.Settings.Default.Salles_DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Pro_SallesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Pro_SallesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Pro_SallesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Pro_SallesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
		
		public System.Data.Linq.Table<UserSettingsProfileProperty> UserSettingsProfileProperties
		{
			get
			{
				return this.GetTable<UserSettingsProfileProperty>();
			}
		}
		
		public System.Data.Linq.Table<Company_Info> Company_Infos
		{
			get
			{
				return this.GetTable<Company_Info>();
			}
		}
		
		public System.Data.Linq.Table<Drower> Drowers
		{
			get
			{
				return this.GetTable<Drower>();
			}
		}
		
		public System.Data.Linq.Table<Invoice_Detail> Invoice_Details
		{
			get
			{
				return this.GetTable<Invoice_Detail>();
			}
		}
		
		public System.Data.Linq.Table<Invoice_Header> Invoice_Headers
		{
			get
			{
				return this.GetTable<Invoice_Header>();
			}
		}
		
		public System.Data.Linq.Table<Journal> Journals
		{
			get
			{
				return this.GetTable<Journal>();
			}
		}
		
		public System.Data.Linq.Table<Product_Category> Product_Categories
		{
			get
			{
				return this.GetTable<Product_Category>();
			}
		}
		
		public System.Data.Linq.Table<Product_Unit> Product_Units
		{
			get
			{
				return this.GetTable<Product_Unit>();
			}
		}
		
		public System.Data.Linq.Table<Store_Log> Store_Logs
		{
			get
			{
				return this.GetTable<Store_Log>();
			}
		}
		
		public System.Data.Linq.Table<Store> Stores
		{
			get
			{
				return this.GetTable<Store>();
			}
		}
		
		public System.Data.Linq.Table<Units_name> Units_names
		{
			get
			{
				return this.GetTable<Units_name>();
			}
		}
		
		public System.Data.Linq.Table<User_Access_Profile_Detail> User_Access_Profile_Details
		{
			get
			{
				return this.GetTable<User_Access_Profile_Detail>();
			}
		}
		
		public System.Data.Linq.Table<User_Access_Profile_Name> User_Access_Profile_Names
		{
			get
			{
				return this.GetTable<User_Access_Profile_Name>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<UserSettingsProfile> UserSettingsProfiles
		{
			get
			{
				return this.GetTable<UserSettingsProfile>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		public System.Data.Linq.Table<CustomersAndVendor> CustomersAndVendors
		{
			get
			{
				return this.GetTable<CustomersAndVendor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Accounts")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserSettingsProfileProperties")]
	public partial class UserSettingsProfileProperty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _Profile_ID;
		
		private string _Property_Name;
		
		private System.Data.Linq.Binary _Property_Value;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnProfile_IDChanging(int value);
    partial void OnProfile_IDChanged();
    partial void OnProperty_NameChanging(string value);
    partial void OnProperty_NameChanged();
    partial void OnProperty_ValueChanging(System.Data.Linq.Binary value);
    partial void OnProperty_ValueChanged();
    #endregion
		
		public UserSettingsProfileProperty()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profile_ID", DbType="Int NOT NULL")]
		public int Profile_ID
		{
			get
			{
				return this._Profile_ID;
			}
			set
			{
				if ((this._Profile_ID != value))
				{
					this.OnProfile_IDChanging(value);
					this.SendPropertyChanging();
					this._Profile_ID = value;
					this.SendPropertyChanged("Profile_ID");
					this.OnProfile_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Property_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Property_Name
		{
			get
			{
				return this._Property_Name;
			}
			set
			{
				if ((this._Property_Name != value))
				{
					this.OnProperty_NameChanging(value);
					this.SendPropertyChanging();
					this._Property_Name = value;
					this.SendPropertyChanged("Property_Name");
					this.OnProperty_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Property_Value", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Property_Value
		{
			get
			{
				return this._Property_Value;
			}
			set
			{
				if ((this._Property_Value != value))
				{
					this.OnProperty_ValueChanging(value);
					this.SendPropertyChanging();
					this._Property_Value = value;
					this.SendPropertyChanged("Property_Value");
					this.OnProperty_ValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Company_Info")]
	public partial class Company_Info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _name;
		
		private string _mobile;
		
		private string _phone;
		
		private string _address;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    #endregion
		
		public Company_Info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="NVarChar(MAX)")]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this.OnmobileChanging(value);
					this.SendPropertyChanging();
					this._mobile = value;
					this.SendPropertyChanged("mobile");
					this.OnmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(MAX)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(MAX)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Drowers")]
	public partial class Drower : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _name;
		
		private int _account_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onaccount_idChanging(int value);
    partial void Onaccount_idChanged();
    #endregion
		
		public Drower()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_id", DbType="Int NOT NULL")]
		public int account_id
		{
			get
			{
				return this._account_id;
			}
			set
			{
				if ((this._account_id != value))
				{
					this.Onaccount_idChanging(value);
					this.SendPropertyChanging();
					this._account_id = value;
					this.SendPropertyChanged("account_id");
					this.Onaccount_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Invoice_Details")]
	public partial class Invoice_Detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _invoice_id;
		
		private int _item_id;
		
		private int _item_unit_id;
		
		private double _item_qty;
		
		private double _price;
		
		private double _total_price;
		
		private double _cost_value;
		
		private double _total_cost_value;
		
		private double _discount;
		
		private double _discount_value;
		
		private int _store_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Oninvoice_idChanging(int value);
    partial void Oninvoice_idChanged();
    partial void Onitem_idChanging(int value);
    partial void Onitem_idChanged();
    partial void Onitem_unit_idChanging(int value);
    partial void Onitem_unit_idChanged();
    partial void Onitem_qtyChanging(double value);
    partial void Onitem_qtyChanged();
    partial void OnpriceChanging(double value);
    partial void OnpriceChanged();
    partial void Ontotal_priceChanging(double value);
    partial void Ontotal_priceChanged();
    partial void Oncost_valueChanging(double value);
    partial void Oncost_valueChanged();
    partial void Ontotal_cost_valueChanging(double value);
    partial void Ontotal_cost_valueChanged();
    partial void OndiscountChanging(double value);
    partial void OndiscountChanged();
    partial void Ondiscount_valueChanging(double value);
    partial void Ondiscount_valueChanged();
    partial void Onstore_idChanging(int value);
    partial void Onstore_idChanged();
    #endregion
		
		public Invoice_Detail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invoice_id", DbType="Int NOT NULL")]
		public int invoice_id
		{
			get
			{
				return this._invoice_id;
			}
			set
			{
				if ((this._invoice_id != value))
				{
					this.Oninvoice_idChanging(value);
					this.SendPropertyChanging();
					this._invoice_id = value;
					this.SendPropertyChanged("invoice_id");
					this.Oninvoice_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_id", DbType="Int NOT NULL")]
		public int item_id
		{
			get
			{
				return this._item_id;
			}
			set
			{
				if ((this._item_id != value))
				{
					this.Onitem_idChanging(value);
					this.SendPropertyChanging();
					this._item_id = value;
					this.SendPropertyChanged("item_id");
					this.Onitem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_unit_id", DbType="Int NOT NULL")]
		public int item_unit_id
		{
			get
			{
				return this._item_unit_id;
			}
			set
			{
				if ((this._item_unit_id != value))
				{
					this.Onitem_unit_idChanging(value);
					this.SendPropertyChanging();
					this._item_unit_id = value;
					this.SendPropertyChanged("item_unit_id");
					this.Onitem_unit_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_qty", DbType="Float NOT NULL")]
		public double item_qty
		{
			get
			{
				return this._item_qty;
			}
			set
			{
				if ((this._item_qty != value))
				{
					this.Onitem_qtyChanging(value);
					this.SendPropertyChanging();
					this._item_qty = value;
					this.SendPropertyChanged("item_qty");
					this.Onitem_qtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float NOT NULL")]
		public double price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_price", DbType="Float NOT NULL")]
		public double total_price
		{
			get
			{
				return this._total_price;
			}
			set
			{
				if ((this._total_price != value))
				{
					this.Ontotal_priceChanging(value);
					this.SendPropertyChanging();
					this._total_price = value;
					this.SendPropertyChanged("total_price");
					this.Ontotal_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cost_value", DbType="Float NOT NULL")]
		public double cost_value
		{
			get
			{
				return this._cost_value;
			}
			set
			{
				if ((this._cost_value != value))
				{
					this.Oncost_valueChanging(value);
					this.SendPropertyChanging();
					this._cost_value = value;
					this.SendPropertyChanged("cost_value");
					this.Oncost_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_cost_value", DbType="Float NOT NULL")]
		public double total_cost_value
		{
			get
			{
				return this._total_cost_value;
			}
			set
			{
				if ((this._total_cost_value != value))
				{
					this.Ontotal_cost_valueChanging(value);
					this.SendPropertyChanging();
					this._total_cost_value = value;
					this.SendPropertyChanged("total_cost_value");
					this.Ontotal_cost_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount", DbType="Float NOT NULL")]
		public double discount
		{
			get
			{
				return this._discount;
			}
			set
			{
				if ((this._discount != value))
				{
					this.OndiscountChanging(value);
					this.SendPropertyChanging();
					this._discount = value;
					this.SendPropertyChanged("discount");
					this.OndiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_value", DbType="Float NOT NULL")]
		public double discount_value
		{
			get
			{
				return this._discount_value;
			}
			set
			{
				if ((this._discount_value != value))
				{
					this.Ondiscount_valueChanging(value);
					this.SendPropertyChanging();
					this._discount_value = value;
					this.SendPropertyChanged("discount_value");
					this.Ondiscount_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_store_id", DbType="Int NOT NULL")]
		public int store_id
		{
			get
			{
				return this._store_id;
			}
			set
			{
				if ((this._store_id != value))
				{
					this.Onstore_idChanging(value);
					this.SendPropertyChanging();
					this._store_id = value;
					this.SendPropertyChanged("store_id");
					this.Onstore_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Invoice_Header")]
	public partial class Invoice_Header : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private byte _invoice_type;
		
		private string _code;
		
		private byte _part_type;
		
		private int _part_id;
		
		private System.DateTime _date;
		
		private System.Nullable<System.DateTime> _deliviry_date;
		
		private int _branch;
		
		private string _notes;
		
		private System.Nullable<System.DateTime> _post_date;
		
		private bool _posted_to_store;
		
		private double _total;
		
		private double _discount_value;
		
		private double _discount_ratio;
		
		private double _tax;
		
		private double _tax_value;
		
		private double _expences;
		
		private double _net;
		
		private double _paid;
		
		private int _drower;
		
		private double _remaing;
		
		private string _shipping_address;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Oninvoice_typeChanging(byte value);
    partial void Oninvoice_typeChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void Onpart_typeChanging(byte value);
    partial void Onpart_typeChanged();
    partial void Onpart_idChanging(int value);
    partial void Onpart_idChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    partial void Ondeliviry_dateChanging(System.Nullable<System.DateTime> value);
    partial void Ondeliviry_dateChanged();
    partial void OnbranchChanging(int value);
    partial void OnbranchChanged();
    partial void OnnotesChanging(string value);
    partial void OnnotesChanged();
    partial void Onpost_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onpost_dateChanged();
    partial void Onposted_to_storeChanging(bool value);
    partial void Onposted_to_storeChanged();
    partial void OntotalChanging(double value);
    partial void OntotalChanged();
    partial void Ondiscount_valueChanging(double value);
    partial void Ondiscount_valueChanged();
    partial void Ondiscount_ratioChanging(double value);
    partial void Ondiscount_ratioChanged();
    partial void OntaxChanging(double value);
    partial void OntaxChanged();
    partial void Ontax_valueChanging(double value);
    partial void Ontax_valueChanged();
    partial void OnexpencesChanging(double value);
    partial void OnexpencesChanged();
    partial void OnnetChanging(double value);
    partial void OnnetChanged();
    partial void OnpaidChanging(double value);
    partial void OnpaidChanged();
    partial void OndrowerChanging(int value);
    partial void OndrowerChanged();
    partial void OnremaingChanging(double value);
    partial void OnremaingChanged();
    partial void Onshipping_addressChanging(string value);
    partial void Onshipping_addressChanged();
    #endregion
		
		public Invoice_Header()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invoice_type", DbType="TinyInt NOT NULL")]
		public byte invoice_type
		{
			get
			{
				return this._invoice_type;
			}
			set
			{
				if ((this._invoice_type != value))
				{
					this.Oninvoice_typeChanging(value);
					this.SendPropertyChanging();
					this._invoice_type = value;
					this.SendPropertyChanged("invoice_type");
					this.Oninvoice_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_type", DbType="TinyInt NOT NULL")]
		public byte part_type
		{
			get
			{
				return this._part_type;
			}
			set
			{
				if ((this._part_type != value))
				{
					this.Onpart_typeChanging(value);
					this.SendPropertyChanging();
					this._part_type = value;
					this.SendPropertyChanged("part_type");
					this.Onpart_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_id", DbType="Int NOT NULL")]
		public int part_id
		{
			get
			{
				return this._part_id;
			}
			set
			{
				if ((this._part_id != value))
				{
					this.Onpart_idChanging(value);
					this.SendPropertyChanging();
					this._part_id = value;
					this.SendPropertyChanged("part_id");
					this.Onpart_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deliviry_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> deliviry_date
		{
			get
			{
				return this._deliviry_date;
			}
			set
			{
				if ((this._deliviry_date != value))
				{
					this.Ondeliviry_dateChanging(value);
					this.SendPropertyChanging();
					this._deliviry_date = value;
					this.SendPropertyChanged("deliviry_date");
					this.Ondeliviry_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branch", DbType="Int NOT NULL")]
		public int branch
		{
			get
			{
				return this._branch;
			}
			set
			{
				if ((this._branch != value))
				{
					this.OnbranchChanging(value);
					this.SendPropertyChanging();
					this._branch = value;
					this.SendPropertyChanged("branch");
					this.OnbranchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="NVarChar(MAX)")]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this.OnnotesChanging(value);
					this.SendPropertyChanging();
					this._notes = value;
					this.SendPropertyChanged("notes");
					this.OnnotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> post_date
		{
			get
			{
				return this._post_date;
			}
			set
			{
				if ((this._post_date != value))
				{
					this.Onpost_dateChanging(value);
					this.SendPropertyChanging();
					this._post_date = value;
					this.SendPropertyChanged("post_date");
					this.Onpost_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_posted_to_store", DbType="Bit NOT NULL")]
		public bool posted_to_store
		{
			get
			{
				return this._posted_to_store;
			}
			set
			{
				if ((this._posted_to_store != value))
				{
					this.Onposted_to_storeChanging(value);
					this.SendPropertyChanging();
					this._posted_to_store = value;
					this.SendPropertyChanged("posted_to_store");
					this.Onposted_to_storeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Float NOT NULL")]
		public double total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_value", DbType="Float NOT NULL")]
		public double discount_value
		{
			get
			{
				return this._discount_value;
			}
			set
			{
				if ((this._discount_value != value))
				{
					this.Ondiscount_valueChanging(value);
					this.SendPropertyChanging();
					this._discount_value = value;
					this.SendPropertyChanged("discount_value");
					this.Ondiscount_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_ratio", DbType="Float NOT NULL")]
		public double discount_ratio
		{
			get
			{
				return this._discount_ratio;
			}
			set
			{
				if ((this._discount_ratio != value))
				{
					this.Ondiscount_ratioChanging(value);
					this.SendPropertyChanging();
					this._discount_ratio = value;
					this.SendPropertyChanged("discount_ratio");
					this.Ondiscount_ratioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tax", DbType="Float NOT NULL")]
		public double tax
		{
			get
			{
				return this._tax;
			}
			set
			{
				if ((this._tax != value))
				{
					this.OntaxChanging(value);
					this.SendPropertyChanging();
					this._tax = value;
					this.SendPropertyChanged("tax");
					this.OntaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tax_value", DbType="Float NOT NULL")]
		public double tax_value
		{
			get
			{
				return this._tax_value;
			}
			set
			{
				if ((this._tax_value != value))
				{
					this.Ontax_valueChanging(value);
					this.SendPropertyChanging();
					this._tax_value = value;
					this.SendPropertyChanged("tax_value");
					this.Ontax_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expences", DbType="Float NOT NULL")]
		public double expences
		{
			get
			{
				return this._expences;
			}
			set
			{
				if ((this._expences != value))
				{
					this.OnexpencesChanging(value);
					this.SendPropertyChanging();
					this._expences = value;
					this.SendPropertyChanged("expences");
					this.OnexpencesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_net", DbType="Float NOT NULL")]
		public double net
		{
			get
			{
				return this._net;
			}
			set
			{
				if ((this._net != value))
				{
					this.OnnetChanging(value);
					this.SendPropertyChanging();
					this._net = value;
					this.SendPropertyChanged("net");
					this.OnnetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paid", DbType="Float NOT NULL")]
		public double paid
		{
			get
			{
				return this._paid;
			}
			set
			{
				if ((this._paid != value))
				{
					this.OnpaidChanging(value);
					this.SendPropertyChanging();
					this._paid = value;
					this.SendPropertyChanged("paid");
					this.OnpaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drower", DbType="Int NOT NULL")]
		public int drower
		{
			get
			{
				return this._drower;
			}
			set
			{
				if ((this._drower != value))
				{
					this.OndrowerChanging(value);
					this.SendPropertyChanging();
					this._drower = value;
					this.SendPropertyChanged("drower");
					this.OndrowerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remaing", DbType="Float NOT NULL")]
		public double remaing
		{
			get
			{
				return this._remaing;
			}
			set
			{
				if ((this._remaing != value))
				{
					this.OnremaingChanging(value);
					this.SendPropertyChanging();
					this._remaing = value;
					this.SendPropertyChanged("remaing");
					this.OnremaingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shipping_address", DbType="NVarChar(MAX)")]
		public string shipping_address
		{
			get
			{
				return this._shipping_address;
			}
			set
			{
				if ((this._shipping_address != value))
				{
					this.Onshipping_addressChanging(value);
					this.SendPropertyChanging();
					this._shipping_address = value;
					this.SendPropertyChanged("shipping_address");
					this.Onshipping_addressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Journals")]
	public partial class Journal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private long _Code;
		
		private int _Account_ID;
		
		private double _Debit;
		
		private double _Credit;
		
		private System.DateTime _Insert_Date;
		
		private byte _Source_Type;
		
		private int _Source_ID;
		
		private string _Notes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnCodeChanging(long value);
    partial void OnCodeChanged();
    partial void OnAccount_IDChanging(int value);
    partial void OnAccount_IDChanged();
    partial void OnDebitChanging(double value);
    partial void OnDebitChanged();
    partial void OnCreditChanging(double value);
    partial void OnCreditChanged();
    partial void OnInsert_DateChanging(System.DateTime value);
    partial void OnInsert_DateChanged();
    partial void OnSource_TypeChanging(byte value);
    partial void OnSource_TypeChanged();
    partial void OnSource_IDChanging(int value);
    partial void OnSource_IDChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    #endregion
		
		public Journal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="BigInt NOT NULL")]
		public long Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account_ID", DbType="Int NOT NULL")]
		public int Account_ID
		{
			get
			{
				return this._Account_ID;
			}
			set
			{
				if ((this._Account_ID != value))
				{
					this.OnAccount_IDChanging(value);
					this.SendPropertyChanging();
					this._Account_ID = value;
					this.SendPropertyChanged("Account_ID");
					this.OnAccount_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Debit", DbType="Float NOT NULL")]
		public double Debit
		{
			get
			{
				return this._Debit;
			}
			set
			{
				if ((this._Debit != value))
				{
					this.OnDebitChanging(value);
					this.SendPropertyChanging();
					this._Debit = value;
					this.SendPropertyChanged("Debit");
					this.OnDebitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Credit", DbType="Float NOT NULL")]
		public double Credit
		{
			get
			{
				return this._Credit;
			}
			set
			{
				if ((this._Credit != value))
				{
					this.OnCreditChanging(value);
					this.SendPropertyChanging();
					this._Credit = value;
					this.SendPropertyChanged("Credit");
					this.OnCreditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Insert_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Insert_Date
		{
			get
			{
				return this._Insert_Date;
			}
			set
			{
				if ((this._Insert_Date != value))
				{
					this.OnInsert_DateChanging(value);
					this.SendPropertyChanging();
					this._Insert_Date = value;
					this.SendPropertyChanged("Insert_Date");
					this.OnInsert_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source_Type", DbType="TinyInt NOT NULL")]
		public byte Source_Type
		{
			get
			{
				return this._Source_Type;
			}
			set
			{
				if ((this._Source_Type != value))
				{
					this.OnSource_TypeChanging(value);
					this.SendPropertyChanging();
					this._Source_Type = value;
					this.SendPropertyChanged("Source_Type");
					this.OnSource_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source_ID", DbType="Int NOT NULL")]
		public int Source_ID
		{
			get
			{
				return this._Source_ID;
			}
			set
			{
				if ((this._Source_ID != value))
				{
					this.OnSource_IDChanging(value);
					this.SendPropertyChanging();
					this._Source_ID = value;
					this.SendPropertyChanged("Source_ID");
					this.OnSource_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product_Category")]
	public partial class Product_Category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _parent_ID;
		
		private string _name;
		
		private string _number;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onparent_IDChanging(System.Nullable<int> value);
    partial void Onparent_IDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnnumberChanging(string value);
    partial void OnnumberChanged();
    #endregion
		
		public Product_Category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_ID", DbType="Int")]
		public System.Nullable<int> parent_ID
		{
			get
			{
				return this._parent_ID;
			}
			set
			{
				if ((this._parent_ID != value))
				{
					this.Onparent_IDChanging(value);
					this.SendPropertyChanging();
					this._parent_ID = value;
					this.SendPropertyChanged("parent_ID");
					this.Onparent_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this.OnnumberChanging(value);
					this.SendPropertyChanging();
					this._number = value;
					this.SendPropertyChanged("number");
					this.OnnumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product_Units")]
	public partial class Product_Unit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _product_id;
		
		private int _unit_id;
		
		private double _factor;
		
		private double _buy_price;
		
		private double _sell_price;
		
		private double _sell_discount;
		
		private string _barcode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onproduct_idChanging(int value);
    partial void Onproduct_idChanged();
    partial void Onunit_idChanging(int value);
    partial void Onunit_idChanged();
    partial void OnfactorChanging(double value);
    partial void OnfactorChanged();
    partial void Onbuy_priceChanging(double value);
    partial void Onbuy_priceChanged();
    partial void Onsell_priceChanging(double value);
    partial void Onsell_priceChanged();
    partial void Onsell_discountChanging(double value);
    partial void Onsell_discountChanged();
    partial void OnbarcodeChanging(string value);
    partial void OnbarcodeChanged();
    #endregion
		
		public Product_Unit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Int NOT NULL")]
		public int product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unit_id", DbType="Int NOT NULL")]
		public int unit_id
		{
			get
			{
				return this._unit_id;
			}
			set
			{
				if ((this._unit_id != value))
				{
					this.Onunit_idChanging(value);
					this.SendPropertyChanging();
					this._unit_id = value;
					this.SendPropertyChanged("unit_id");
					this.Onunit_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factor", DbType="Float NOT NULL")]
		public double factor
		{
			get
			{
				return this._factor;
			}
			set
			{
				if ((this._factor != value))
				{
					this.OnfactorChanging(value);
					this.SendPropertyChanging();
					this._factor = value;
					this.SendPropertyChanged("factor");
					this.OnfactorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_buy_price", DbType="Float NOT NULL")]
		public double buy_price
		{
			get
			{
				return this._buy_price;
			}
			set
			{
				if ((this._buy_price != value))
				{
					this.Onbuy_priceChanging(value);
					this.SendPropertyChanging();
					this._buy_price = value;
					this.SendPropertyChanged("buy_price");
					this.Onbuy_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sell_price", DbType="Float NOT NULL")]
		public double sell_price
		{
			get
			{
				return this._sell_price;
			}
			set
			{
				if ((this._sell_price != value))
				{
					this.Onsell_priceChanging(value);
					this.SendPropertyChanging();
					this._sell_price = value;
					this.SendPropertyChanged("sell_price");
					this.Onsell_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sell_discount", DbType="Float NOT NULL")]
		public double sell_discount
		{
			get
			{
				return this._sell_discount;
			}
			set
			{
				if ((this._sell_discount != value))
				{
					this.Onsell_discountChanging(value);
					this.SendPropertyChanging();
					this._sell_discount = value;
					this.SendPropertyChanged("sell_discount");
					this.Onsell_discountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barcode", DbType="NVarChar(MAX)")]
		public string barcode
		{
			get
			{
				return this._barcode;
			}
			set
			{
				if ((this._barcode != value))
				{
					this.OnbarcodeChanging(value);
					this.SendPropertyChanging();
					this._barcode = value;
					this.SendPropertyChanged("barcode");
					this.OnbarcodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Store_Log")]
	public partial class Store_Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private byte _source_type;
		
		private int _source_id;
		
		private int _product_id;
		
		private int _store_id;
		
		private double _qty;
		
		private bool _is_in_transaction;
		
		private double _cost_value;
		
		private System.DateTime _insert_time;
		
		private string _notes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onsource_typeChanging(byte value);
    partial void Onsource_typeChanged();
    partial void Onsource_idChanging(int value);
    partial void Onsource_idChanged();
    partial void Onproduct_idChanging(int value);
    partial void Onproduct_idChanged();
    partial void Onstore_idChanging(int value);
    partial void Onstore_idChanged();
    partial void OnqtyChanging(double value);
    partial void OnqtyChanged();
    partial void Onis_in_transactionChanging(bool value);
    partial void Onis_in_transactionChanged();
    partial void Oncost_valueChanging(double value);
    partial void Oncost_valueChanged();
    partial void Oninsert_timeChanging(System.DateTime value);
    partial void Oninsert_timeChanged();
    partial void OnnotesChanging(string value);
    partial void OnnotesChanged();
    #endregion
		
		public Store_Log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_type", DbType="TinyInt NOT NULL")]
		public byte source_type
		{
			get
			{
				return this._source_type;
			}
			set
			{
				if ((this._source_type != value))
				{
					this.Onsource_typeChanging(value);
					this.SendPropertyChanging();
					this._source_type = value;
					this.SendPropertyChanged("source_type");
					this.Onsource_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_id", DbType="Int NOT NULL")]
		public int source_id
		{
			get
			{
				return this._source_id;
			}
			set
			{
				if ((this._source_id != value))
				{
					this.Onsource_idChanging(value);
					this.SendPropertyChanging();
					this._source_id = value;
					this.SendPropertyChanged("source_id");
					this.Onsource_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Int NOT NULL")]
		public int product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_store_id", DbType="Int NOT NULL")]
		public int store_id
		{
			get
			{
				return this._store_id;
			}
			set
			{
				if ((this._store_id != value))
				{
					this.Onstore_idChanging(value);
					this.SendPropertyChanging();
					this._store_id = value;
					this.SendPropertyChanged("store_id");
					this.Onstore_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qty", DbType="Float NOT NULL")]
		public double qty
		{
			get
			{
				return this._qty;
			}
			set
			{
				if ((this._qty != value))
				{
					this.OnqtyChanging(value);
					this.SendPropertyChanging();
					this._qty = value;
					this.SendPropertyChanged("qty");
					this.OnqtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_in_transaction", DbType="Bit NOT NULL")]
		public bool is_in_transaction
		{
			get
			{
				return this._is_in_transaction;
			}
			set
			{
				if ((this._is_in_transaction != value))
				{
					this.Onis_in_transactionChanging(value);
					this.SendPropertyChanging();
					this._is_in_transaction = value;
					this.SendPropertyChanged("is_in_transaction");
					this.Onis_in_transactionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cost_value", DbType="Float NOT NULL")]
		public double cost_value
		{
			get
			{
				return this._cost_value;
			}
			set
			{
				if ((this._cost_value != value))
				{
					this.Oncost_valueChanging(value);
					this.SendPropertyChanging();
					this._cost_value = value;
					this.SendPropertyChanged("cost_value");
					this.Oncost_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_time", DbType="DateTime NOT NULL")]
		public System.DateTime insert_time
		{
			get
			{
				return this._insert_time;
			}
			set
			{
				if ((this._insert_time != value))
				{
					this.Oninsert_timeChanging(value);
					this.SendPropertyChanging();
					this._insert_time = value;
					this.SendPropertyChanged("insert_time");
					this.Oninsert_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this.OnnotesChanging(value);
					this.SendPropertyChanging();
					this._notes = value;
					this.SendPropertyChanged("notes");
					this.OnnotesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Stores")]
	public partial class Store : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _name;
		
		private int _Salles_Account_ID;
		
		private int _Salles_Return_Account_ID;
		
		private int _Inventory_Account_ID;
		
		private int _Cost_Of_Sold_Goods_Account_ID;
		
		private int _Discount_Received_Account_ID;
		
		private int _Discount_Allowed_Account_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnSalles_Account_IDChanging(int value);
    partial void OnSalles_Account_IDChanged();
    partial void OnSalles_Return_Account_IDChanging(int value);
    partial void OnSalles_Return_Account_IDChanged();
    partial void OnInventory_Account_IDChanging(int value);
    partial void OnInventory_Account_IDChanged();
    partial void OnCost_Of_Sold_Goods_Account_IDChanging(int value);
    partial void OnCost_Of_Sold_Goods_Account_IDChanged();
    partial void OnDiscount_Received_Account_IDChanging(int value);
    partial void OnDiscount_Received_Account_IDChanged();
    partial void OnDiscount_Allowed_Account_IDChanging(int value);
    partial void OnDiscount_Allowed_Account_IDChanged();
    #endregion
		
		public Store()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salles_Account_ID", DbType="Int NOT NULL")]
		public int Salles_Account_ID
		{
			get
			{
				return this._Salles_Account_ID;
			}
			set
			{
				if ((this._Salles_Account_ID != value))
				{
					this.OnSalles_Account_IDChanging(value);
					this.SendPropertyChanging();
					this._Salles_Account_ID = value;
					this.SendPropertyChanged("Salles_Account_ID");
					this.OnSalles_Account_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salles_Return_Account_ID", DbType="Int NOT NULL")]
		public int Salles_Return_Account_ID
		{
			get
			{
				return this._Salles_Return_Account_ID;
			}
			set
			{
				if ((this._Salles_Return_Account_ID != value))
				{
					this.OnSalles_Return_Account_IDChanging(value);
					this.SendPropertyChanging();
					this._Salles_Return_Account_ID = value;
					this.SendPropertyChanged("Salles_Return_Account_ID");
					this.OnSalles_Return_Account_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inventory_Account_ID", DbType="Int NOT NULL")]
		public int Inventory_Account_ID
		{
			get
			{
				return this._Inventory_Account_ID;
			}
			set
			{
				if ((this._Inventory_Account_ID != value))
				{
					this.OnInventory_Account_IDChanging(value);
					this.SendPropertyChanging();
					this._Inventory_Account_ID = value;
					this.SendPropertyChanged("Inventory_Account_ID");
					this.OnInventory_Account_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost_Of_Sold_Goods_Account_ID", DbType="Int NOT NULL")]
		public int Cost_Of_Sold_Goods_Account_ID
		{
			get
			{
				return this._Cost_Of_Sold_Goods_Account_ID;
			}
			set
			{
				if ((this._Cost_Of_Sold_Goods_Account_ID != value))
				{
					this.OnCost_Of_Sold_Goods_Account_IDChanging(value);
					this.SendPropertyChanging();
					this._Cost_Of_Sold_Goods_Account_ID = value;
					this.SendPropertyChanged("Cost_Of_Sold_Goods_Account_ID");
					this.OnCost_Of_Sold_Goods_Account_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discount_Received_Account_ID", DbType="Int NOT NULL")]
		public int Discount_Received_Account_ID
		{
			get
			{
				return this._Discount_Received_Account_ID;
			}
			set
			{
				if ((this._Discount_Received_Account_ID != value))
				{
					this.OnDiscount_Received_Account_IDChanging(value);
					this.SendPropertyChanging();
					this._Discount_Received_Account_ID = value;
					this.SendPropertyChanged("Discount_Received_Account_ID");
					this.OnDiscount_Received_Account_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discount_Allowed_Account_ID", DbType="Int NOT NULL")]
		public int Discount_Allowed_Account_ID
		{
			get
			{
				return this._Discount_Allowed_Account_ID;
			}
			set
			{
				if ((this._Discount_Allowed_Account_ID != value))
				{
					this.OnDiscount_Allowed_Account_IDChanging(value);
					this.SendPropertyChanging();
					this._Discount_Allowed_Account_ID = value;
					this.SendPropertyChanged("Discount_Allowed_Account_ID");
					this.OnDiscount_Allowed_Account_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Units_name")]
	public partial class Units_name : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Units_name()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.User_Access_Profile_Details")]
	public partial class User_Access_Profile_Detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _Profile_ID;
		
		private int _Screen_ID;
		
		private bool _Can_Show;
		
		private bool _Can_Open;
		
		private bool _Can_Add;
		
		private bool _Can_Edit;
		
		private bool _Can_Delete;
		
		private bool _Can_Print;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnProfile_IDChanging(int value);
    partial void OnProfile_IDChanged();
    partial void OnScreen_IDChanging(int value);
    partial void OnScreen_IDChanged();
    partial void OnCan_ShowChanging(bool value);
    partial void OnCan_ShowChanged();
    partial void OnCan_OpenChanging(bool value);
    partial void OnCan_OpenChanged();
    partial void OnCan_AddChanging(bool value);
    partial void OnCan_AddChanged();
    partial void OnCan_EditChanging(bool value);
    partial void OnCan_EditChanged();
    partial void OnCan_DeleteChanging(bool value);
    partial void OnCan_DeleteChanged();
    partial void OnCan_PrintChanging(bool value);
    partial void OnCan_PrintChanged();
    #endregion
		
		public User_Access_Profile_Detail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profile_ID", DbType="Int NOT NULL")]
		public int Profile_ID
		{
			get
			{
				return this._Profile_ID;
			}
			set
			{
				if ((this._Profile_ID != value))
				{
					this.OnProfile_IDChanging(value);
					this.SendPropertyChanging();
					this._Profile_ID = value;
					this.SendPropertyChanged("Profile_ID");
					this.OnProfile_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Screen_ID", DbType="Int NOT NULL")]
		public int Screen_ID
		{
			get
			{
				return this._Screen_ID;
			}
			set
			{
				if ((this._Screen_ID != value))
				{
					this.OnScreen_IDChanging(value);
					this.SendPropertyChanging();
					this._Screen_ID = value;
					this.SendPropertyChanged("Screen_ID");
					this.OnScreen_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Can_Show", DbType="Bit NOT NULL")]
		public bool Can_Show
		{
			get
			{
				return this._Can_Show;
			}
			set
			{
				if ((this._Can_Show != value))
				{
					this.OnCan_ShowChanging(value);
					this.SendPropertyChanging();
					this._Can_Show = value;
					this.SendPropertyChanged("Can_Show");
					this.OnCan_ShowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Can_Open", DbType="Bit NOT NULL")]
		public bool Can_Open
		{
			get
			{
				return this._Can_Open;
			}
			set
			{
				if ((this._Can_Open != value))
				{
					this.OnCan_OpenChanging(value);
					this.SendPropertyChanging();
					this._Can_Open = value;
					this.SendPropertyChanged("Can_Open");
					this.OnCan_OpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Can_Add", DbType="Bit NOT NULL")]
		public bool Can_Add
		{
			get
			{
				return this._Can_Add;
			}
			set
			{
				if ((this._Can_Add != value))
				{
					this.OnCan_AddChanging(value);
					this.SendPropertyChanging();
					this._Can_Add = value;
					this.SendPropertyChanged("Can_Add");
					this.OnCan_AddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Can_Edit", DbType="Bit NOT NULL")]
		public bool Can_Edit
		{
			get
			{
				return this._Can_Edit;
			}
			set
			{
				if ((this._Can_Edit != value))
				{
					this.OnCan_EditChanging(value);
					this.SendPropertyChanging();
					this._Can_Edit = value;
					this.SendPropertyChanged("Can_Edit");
					this.OnCan_EditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Can_Delete", DbType="Bit NOT NULL")]
		public bool Can_Delete
		{
			get
			{
				return this._Can_Delete;
			}
			set
			{
				if ((this._Can_Delete != value))
				{
					this.OnCan_DeleteChanging(value);
					this.SendPropertyChanging();
					this._Can_Delete = value;
					this.SendPropertyChanged("Can_Delete");
					this.OnCan_DeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Can_Print", DbType="Bit NOT NULL")]
		public bool Can_Print
		{
			get
			{
				return this._Can_Print;
			}
			set
			{
				if ((this._Can_Print != value))
				{
					this.OnCan_PrintChanging(value);
					this.SendPropertyChanging();
					this._Can_Print = value;
					this.SendPropertyChanged("Can_Print");
					this.OnCan_PrintChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.User_Access_Profile_Name")]
	public partial class User_Access_Profile_Name : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public User_Access_Profile_Name()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _User_Name;
		
		private string _Password;
		
		private byte _User_Type;
		
		private int _Settings_Profile_ID;
		
		private System.Nullable<int> _Screen_Profile_ID;
		
		private bool _Is_Active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnUser_NameChanging(string value);
    partial void OnUser_NameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnUser_TypeChanging(byte value);
    partial void OnUser_TypeChanged();
    partial void OnSettings_Profile_IDChanging(int value);
    partial void OnSettings_Profile_IDChanged();
    partial void OnScreen_Profile_IDChanging(System.Nullable<int> value);
    partial void OnScreen_Profile_IDChanged();
    partial void OnIs_ActiveChanging(bool value);
    partial void OnIs_ActiveChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string User_Name
		{
			get
			{
				return this._User_Name;
			}
			set
			{
				if ((this._User_Name != value))
				{
					this.OnUser_NameChanging(value);
					this.SendPropertyChanging();
					this._User_Name = value;
					this.SendPropertyChanged("User_Name");
					this.OnUser_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Type", DbType="TinyInt NOT NULL")]
		public byte User_Type
		{
			get
			{
				return this._User_Type;
			}
			set
			{
				if ((this._User_Type != value))
				{
					this.OnUser_TypeChanging(value);
					this.SendPropertyChanging();
					this._User_Type = value;
					this.SendPropertyChanged("User_Type");
					this.OnUser_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Settings_Profile_ID", DbType="Int NOT NULL")]
		public int Settings_Profile_ID
		{
			get
			{
				return this._Settings_Profile_ID;
			}
			set
			{
				if ((this._Settings_Profile_ID != value))
				{
					this.OnSettings_Profile_IDChanging(value);
					this.SendPropertyChanging();
					this._Settings_Profile_ID = value;
					this.SendPropertyChanged("Settings_Profile_ID");
					this.OnSettings_Profile_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Screen_Profile_ID", DbType="Int")]
		public System.Nullable<int> Screen_Profile_ID
		{
			get
			{
				return this._Screen_Profile_ID;
			}
			set
			{
				if ((this._Screen_Profile_ID != value))
				{
					this.OnScreen_Profile_IDChanging(value);
					this.SendPropertyChanging();
					this._Screen_Profile_ID = value;
					this.SendPropertyChanged("Screen_Profile_ID");
					this.OnScreen_Profile_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is_Active", DbType="Bit NOT NULL")]
		public bool Is_Active
		{
			get
			{
				return this._Is_Active;
			}
			set
			{
				if ((this._Is_Active != value))
				{
					this.OnIs_ActiveChanging(value);
					this.SendPropertyChanging();
					this._Is_Active = value;
					this.SendPropertyChanged("Is_Active");
					this.OnIs_ActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserSettingsProfile")]
	public partial class UserSettingsProfile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public UserSettingsProfile()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _code;
		
		private string _name;
		
		private byte _type;
		
		private string _discription;
		
		private bool _is_active;
		
		private System.Data.Linq.Binary _image;
		
		private int _Category_ID;
		
		private byte _CostCalculatingMethod;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OntypeChanging(byte value);
    partial void OntypeChanged();
    partial void OndiscriptionChanging(string value);
    partial void OndiscriptionChanged();
    partial void Onis_activeChanging(bool value);
    partial void Onis_activeChanged();
    partial void OnimageChanging(System.Data.Linq.Binary value);
    partial void OnimageChanged();
    partial void OnCategory_IDChanging(int value);
    partial void OnCategory_IDChanged();
    partial void OnCostCalculatingMethodChanging(byte value);
    partial void OnCostCalculatingMethodChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="TinyInt NOT NULL")]
		public byte type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discription", DbType="NVarChar(MAX)")]
		public string discription
		{
			get
			{
				return this._discription;
			}
			set
			{
				if ((this._discription != value))
				{
					this.OndiscriptionChanging(value);
					this.SendPropertyChanging();
					this._discription = value;
					this.SendPropertyChanged("discription");
					this.OndiscriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_active", DbType="Bit NOT NULL")]
		public bool is_active
		{
			get
			{
				return this._is_active;
			}
			set
			{
				if ((this._is_active != value))
				{
					this.Onis_activeChanging(value);
					this.SendPropertyChanging();
					this._is_active = value;
					this.SendPropertyChanged("is_active");
					this.Onis_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_ID", DbType="Int NOT NULL")]
		public int Category_ID
		{
			get
			{
				return this._Category_ID;
			}
			set
			{
				if ((this._Category_ID != value))
				{
					this.OnCategory_IDChanging(value);
					this.SendPropertyChanging();
					this._Category_ID = value;
					this.SendPropertyChanged("Category_ID");
					this.OnCategory_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostCalculatingMethod", DbType="TinyInt NOT NULL")]
		public byte CostCalculatingMethod
		{
			get
			{
				return this._CostCalculatingMethod;
			}
			set
			{
				if ((this._CostCalculatingMethod != value))
				{
					this.OnCostCalculatingMethodChanging(value);
					this.SendPropertyChanging();
					this._CostCalculatingMethod = value;
					this.SendPropertyChanged("CostCalculatingMethod");
					this.OnCostCalculatingMethodChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomersAndVendors")]
	public partial class CustomersAndVendor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _name;
		
		private string _phone;
		
		private string _mobile;
		
		private string _address;
		
		private bool _Is_Customer;
		
		private int _account_id;
		
		private double _max_Credit;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnIs_CustomerChanging(bool value);
    partial void OnIs_CustomerChanged();
    partial void Onaccount_idChanging(int value);
    partial void Onaccount_idChanged();
    partial void Onmax_CreditChanging(double value);
    partial void Onmax_CreditChanged();
    #endregion
		
		public CustomersAndVendor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(MAX)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="NVarChar(MAX)")]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this.OnmobileChanging(value);
					this.SendPropertyChanging();
					this._mobile = value;
					this.SendPropertyChanged("mobile");
					this.OnmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(MAX)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is_Customer", DbType="Bit NOT NULL")]
		public bool Is_Customer
		{
			get
			{
				return this._Is_Customer;
			}
			set
			{
				if ((this._Is_Customer != value))
				{
					this.OnIs_CustomerChanging(value);
					this.SendPropertyChanging();
					this._Is_Customer = value;
					this.SendPropertyChanged("Is_Customer");
					this.OnIs_CustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_id", DbType="Int NOT NULL")]
		public int account_id
		{
			get
			{
				return this._account_id;
			}
			set
			{
				if ((this._account_id != value))
				{
					this.Onaccount_idChanging(value);
					this.SendPropertyChanging();
					this._account_id = value;
					this.SendPropertyChanged("account_id");
					this.Onaccount_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_Credit", DbType="Float NOT NULL")]
		public double max_Credit
		{
			get
			{
				return this._max_Credit;
			}
			set
			{
				if ((this._max_Credit != value))
				{
					this.Onmax_CreditChanging(value);
					this.SendPropertyChanging();
					this._max_Credit = value;
					this.SendPropertyChanged("max_Credit");
					this.Onmax_CreditChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
